set shell=/bin/zsh
set shiftwidth=4
set tabstop=4
set expandtab
set textwidth=0
set autoindent
set hlsearch
set number
set smartindent
set clipboard=unnamed
set confirm
set mouse=a
set background=dark
set laststatus=2
set smartindent
set cindent
set termguicolors
set encoding=UTF-8
set termguicolors
